// Sync versions of PakList.ParseAsync — normally generated by Zomp.SyncMethodGenerator.
namespace GBX.NET.PAK;

public sealed partial class PakList
{
    public static PakList Parse(Stream stream, string nameKeySalt, string keyStringKeySalt)
        => ParseAsync(stream, nameKeySalt, keyStringKeySalt).GetAwaiter().GetResult();

    public static PakList Parse(Stream stream, PakListGame game = PakListGame.TM)
        => ParseAsync(stream, game).GetAwaiter().GetResult();
}
