// Sync version of OpenGbxFileAsync — normally generated by Zomp.SyncMethodGenerator.
// Required because ImportExternalNodesFromRefTable registers lazy node loaders via pak.OpenGbxFile().
namespace GBX.NET.PAK;

public partial class Pak
{
    public Gbx OpenGbxFile(PakFile file, GbxReadSettings settings = default, bool importExternalNodesFromRefTable = false, IDictionary<string, string>? fileHashes = default)
    {
        using var stream = OpenFile(file, out var encryptionInitializer);

        if (!file.DontUseDummyWrite)
            settings = settings with { EncryptionInitializer = encryptionInitializer };

        var gbx = Gbx.Parse(stream, settings);

        if (gbx.RefTable is not null && importExternalNodesFromRefTable)
            ImportExternalNodesFromRefTable(this, file, gbx.RefTable, settings, fileHashes);

        return gbx;
    }
}
